# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'buildTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
    pod 'Leanplum-iOS-SDK'
    pod 'Leanplum-iOS-UIEditor'
    pod 'Leanplum-iOS-Location'

end

target 'buildTestTests' do
    inherit! :search_paths
end
